{{- if .Values.monitoring.enabled and .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "potatobot.fullname" . }}
  labels:
    {{- include "potatobot.labels" . | nindent 4 }}
    release: {{ .Values.monitoring.serviceMonitor.namespace }}
spec:
  selector:
    matchLabels:
      {{- include "potatobot.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}