apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "potatobot.serviceAccountName" . }}
  labels:
    {{- include "potatobot.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}